[package]
name = "ltc2686"
version = "0.1.0"
edition = "2024"
rust-version = "1.94"
description = "An embedded-hal driver for the AnalogDevices LT2686 DAC."
license = "MIT OR Apache-2.0"
categories = ["embedded", "no-std", "hardware-support"]
keywords = ["embedded-hal", "driver", "device-driver"]
repository = "https://github.com/trappitsch/ltc2686"
readme = "README.md"

[dependencies]
device-driver = { version = "2.1.0", features = ["macros"] }
embedded-hal = "1.0"
embedded-hal-async = { version = "1.0", optional = true }

defmt = { version = "1.0", optional = true }

[dev-dependencies]
embedded-hal-mock = { version = "0.11.1", features = ["embedded-hal-async"] }
pico-de-gallo-hal = "0.7"
rstest = "0.26.1"
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread"] }

[features]
async = ["embedded-hal-async"]
default = ["async"]
blocking = []
defmt = ["dep:defmt", "device-driver/defmt"]

[[example]]
name = "ll_all_channels"
required-features = ["async"]

[[example]]
name = "ll_bipolar"
required-features = ["async"]

[[example]]
name = "ll_crc"
required-features = ["async"]

[[example]]
name = "ll_dither"
required-features = ["async"]

[[example]]
name = "ll_dither_ext"
required-features = ["async"]

[[example]]
name = "ll_simple"
required-features = ["async"]

[[example]]
name = "ll_span"
required-features = ["async"]

[[example]]
name = "ll_toggle"
required-features = ["async"]

[[test]]
name = "test_ll_async"
required-features = ["async"]

[[test]]
name = "test_ll_blocking"
required-features = ["blocking"]
